version: "3"

services:
  postgresdb:
    container_name: postgresdb
    image: postgres:10.23-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=tasks
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=<password>
    volumes:
      - /home/evandro/dockerdata/postgres:/var/lib/postgresql/data
  sonarqube:
    container_name: sonar
    image: sonarqube:9.9.4-community
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.url=jdbc:postgresql://pg-sonar:5432/sonar
    depends_on:
      - pg-sonar
    volumes:
      - /home/evandro/docker/sonar/conf:/opt/sonarqube/conf
      - /home/evandro/docker/sonar/data:/opt/sonarqube/data
      - /home/evandro/docker/sonar/ext:/opt/sonarqube/extensions
      - /home/evandro/docker/sonar/plugin:/opt/sonarqube/lib/bundled-plugins
  pg-sonar:
    container_name: pg-sonar
    image: postgres:9.6
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /home/evandro/docker/sonar/postgres:/var/lib/postgresql
      - /home/evandro/docker/sonar/pstdata:/var/lib/postgresql/data

  selenium-hub:
    image: selenium/hub:3.141.59-zinc
    container_name: selenium-hub
    networks:
      - seleniumGrid
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.141.59-zinc
    container_name: Chrome-1
    networks:
      - seleniumGrid
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=2
      - NODE_MAX_SESSIONS=2

  chrome2:
    image: selenium/node-chrome:3.141.59-zinc
    container_name: Chrome-2
    networks:
      - seleniumGrid
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=2
      - NODE_MAX_SESSIONS=2

networks:
  sonarnet:
  seleniumGrid:

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:

