
   CREATE SEQUENCE  "OPT_PRONT_ELETR"."TIPOPESSOA_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 CACHE 20 NOORDER  NOCYCLE ;

  
  CREATE TABLE "OPT_PRONT_ELETR"."TIPOPESSOA" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"DESCRICAO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "IDTIPOPESSOA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "FASTFOOD"."TIPOPESSOA"."DESCRICAO" IS 'valores validos 0-cliente 1-empresa 2-usuario';


insert into TIPOPESSOA (ID,DESCRICAO) VALUES (TIPOPESSOA_ID_SEQ.nextval, 'OUTROS COLABORADORES');
insert into TIPOPESSOA (ID,DESCRICAO) VALUES (TIPOPESSOA_ID_SEQ.nextval, 'ENFERMEIRO(A)');
insert into TIPOPESSOA (ID,DESCRICAO) VALUES (TIPOPESSOA_ID_SEQ.nextval, 'MÉDICO(A)');
insert into TIPOPESSOA (ID,DESCRICAO) VALUES (TIPOPESSOA_ID_SEQ.nextval, 'ADMINISTRADOR');
COMMIT;
